### ISSUE TITLE
Can one use jitpack to serve the jar?

### ISSUE THREAD

**Issue by carddamom** [signed/junit-cucumber-engine#1]
Instead of having to build the project locally, maybe one could use jitpack (https://jitpack.io/#signed/junit-cucumber-engine/master), to build a jar and add it as a dependency?

**Comment by signed** [comment]
I have not used jitpack before and did not look into this project for a long time.
The dependencies are all outdated and as far as I remember from my last attempt there are a lot of breaking changes.
If you can tell me what I have to do to setup jitpack I can give it a go, PR would be even better :).
